// MEMO Network Activity Investigation

AzureActivity
| where TimeGenerated > ago(24h)
| where ResourceGroup contains "MEMO-RG-Network"
| project
    TimeGenerated,
    Caller,
    OperationNameValue,
    ActivityStatusValue,
    ResourceGroup,
    ResourceId
| order by TimeGenerated desc


// MEMO RBAC Change Investigation

AzureActivity
| where TimeGenerated > ago(24h)
| where OperationNameValue contains "roleAssignments"
| project
    TimeGenerated,
    Caller,
    OperationNameValue,
    ActivityStatusValue,
    ResourceGroup,
    ResourceId
| order by TimeGenerated desc