apiVersion: v1
kind: ConfigMap
metadata:
  name: memo-app-config
  namespace: memo-app
  labels:
    app: memo-secure-app
data:
  ENVIRONMENT: "lab"
  PROJECT_NAME: "MEMO Foundation"
  SECURITY_MODE: "restricted"